[package]
name = "cached_tree_hash"
version = "0.1.0"
authors = ["Michael Sproul <michael@sigmaprime.io>"]
edition = "2021"

[dependencies]
ethereum-types = "0.14.1"
ssz_types = { git = "https://gitlab.com/pulsechaincom/ssz_types.git", tag = "v0.5.2" }
ethereum_hashing = "1.0.0-beta.2"
ethereum_ssz_derive = { git = "https://gitlab.com/pulsechaincom/ethereum_ssz.git", tag = "v0.5.2" }
ethereum_ssz = { git = "https://gitlab.com/pulsechaincom/ethereum_ssz.git", tag = "v0.5.2" }
tree_hash = "0.5.0"
smallvec = "1.6.1"

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"

[features]
arbitrary = ["ethereum-types/arbitrary"]
